### ISSUE TITLE
Dynamic `App` 

### ISSUE THREAD

**Issue by chaadow** [karafka/testing#2]
Hi,
First, Thank you for your work for this gem.

in [these lines](https://github.com/karafka/testing/blob/master/lib/karafka/testing/rspec/helpers.rb#L39-L43), there is a hard coded `App` which actually can differ from one application to another.

I just thought of 2 alternatives: 

1- Maybe ask the gem user to specify a `let(:karafka_app) { MyCustomKarafkaApp }` and then use that. (since you already expect the rspec `subject` to be defined by the user as well)

2-  or perhaps there is a way to get this value from the `Karafka` gem. Actually one way to do so is to do something like this : `Karafka::App.descendants.first` (or `.last`) which returns the class that is defined in `karafka.rb` that inherits from `Karafka::App`.

Or maybe a hybrid approach. However, I'd go for the `Karafka::App.descendants.first`

EDIT: 

@mensfeld A third idea, I just tried `Karafka::App.consumer_groups` in console and it worked and listed all my consumer groups. And since all karafka applications inherit from `Karafka::App` I think this would work.

**Comment by mensfeld** [comment]
Good point! I will take a look at this week and think about the solution. Thank you!

**Comment by mensfeld** [comment]
@nijikon any idea?

**Comment by mensfeld** [comment]
> A third idea, I just tried Karafka::App.consumer_groups in console and it worked and listed all my consumer groups. And since all karafka applications inherit from Karafka::App I think this would work.

Yes. This will work for now but not in the future as the global state is going to be removed. But for the `1.3` we can easily go with that. Fix in progress!
