### ISSUE TITLE
Wrong number of arguments in `subject.topic.deserializer`

### ISSUE THREAD

**Issue by howtwizer** [karafka/testing#3]
Hi, thank's for the gem. 
Have an issue, may be dependent on using this gem with rails. 

```
described_class.new(selected_topic)
=> wrong number of arguments (given 1, expected 0)
```

```
described_class
=> BeaconEventsConsumer
```

../app/consumers/beacon_events_consumer.rb
```
class BeaconEventsConsumer < ApplicationConsumer
  # This method just logs parsed data with Karafka logger
  def consume
    Rails.logger.info "Consumed following message: #{params}"

  end
end
```

../karafka.rb
```
  consumer_groups.draw do
    consumer_group :batched_group do
      topic :beacon_events do
        consumer BeaconEventsConsumer
        batch_consuming false
      end
    end


  end
```

**Comment by mensfeld** [comment]
Could yo provide me with ruby, rails and karafka versions?

**Comment by howtwizer** [comment]
```
ruby '2.6.3'
rails (6.0.0.rc1)
karafka (1.2.12)
```

**Comment by mensfeld** [comment]
Testing lib does **not** work with karafka `1.2`. I'm working with @solnic and several other people to craft the `1.3` release. I will lock it to `1.3`. Really sorry for the confusion :(

**Comment by mensfeld** [comment]
ref: https://github.com/karafka/testing/issues/1

**Comment by howtwizer** [comment]
Ah... may be note it in docs... Thank you in any case.

**Comment by mensfeld** [comment]
closing due to: https://github.com/karafka/testing/pull/4
